---

version: '3'

services:
  app:
    build: .
    ports:
      - '4000:4000'
    volumes:
      - ./src:/app
    depends_on:
      - db
  db:
    image: postgres:11
    ports:
      - '5432:5432'
    volumes:
      - 'dbdata:/var/lib/postgresql/data'

volumes:
  dbdata:
